version: '3.9'

services:
  prod:
    image: phosphorgus/bt-prod
    container_name: baby_tracker
    build:
      dockerfile: Dockerfile
    volumes:
      - .:/src
    command: npm start
    ports:
      - "80:3000"
